First Code Review
Tessyrich/Review-your-project pull request #1
Opened 2022-10-03 17:09 UTC by Tessyrich

Added the necessary comments on the code

2022-10-03 17:33 UTC, Tessyrich reviewed
Changes Required.### 
 You are almost there. But you need to add a little change.

Check and complete the changes below and submit them for re-review also feel free to contact me for any questions using via email, slack, or GitHub.

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +                class="stretched"
Please use an indention of two lines that is [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +                <option value="Full Time job">Full Time job</option>
Please use an indention of two lines that is [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +                <input
Please use an indention of two lines that is [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +                cols="30"
Please use an indention of two lines that is [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +</html>
Please use an indention of two lines that is [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2022-10-03 17:33 UTC, Tessyrich commented on index.html
> +            <div id="radio-buttons">
Please use a section tag or any other tag. This is HTML & CSS best practices

2022-10-03 17:58 UTC, aimalamiri requested changes
Hi @Tessyrich, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- Good job for using the right GitHub Flow 💯
- Awesome code review comments 🗃️

## Required Changes ♻️
You did a good job! You added respectful comments, but please make sure to add some more description to your code comments.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 18:43 UTC, Tessyrich reviewed
Required changes### 
Good job so far!
 There are minor issues you still need to work on.
Kindly check the comments under the review and submit for re-review after making changes.

2022-10-03 18:43 UTC, Tessyrich commented on index.html
> +            /><br />
As requested in the project requirement: Please use an indentation of two lines for all your documents. This is the convention and also the [best HTML & CSS practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-10-03 18:43 UTC, Tessyrich commented on index.html
> +            <div id="radio-buttons">
Kindly use a section tag or any other tag other than div to wrap a container. This best practices fro HTML see,amtics

2022-10-03 18:43 UTC, Tessyrich commented on index.html
> +                <input
As requested in the project requirement: Please use an indentation of two lines for all your documents. This is the convention and also the [best HTML & CSS practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2022-10-03 18:47 UTC, aimalamiri approved these changes
Hi @Tessyrich, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![ApprovedDavieGIF](https://user-images.githubusercontent.com/34779928/191333120-c0c2ce83-28e1-4dbc-aac1-09e467f7a8bd.gif)


## Highlights


- Good job for using the right GitHub Flow 💯
- Review comments are descriptive and respectful 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-04 09:13 UTC, merged

2022-12-05 16:33 UTC, andgarzonmal commented
Hi @Tessyrich , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Nice job reviewing your project ✔️ 
- Good implementations  ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._